### ISSUE TITLE
Not a valid po and pot file

### ISSUE THREAD

**Issue by tripatwhat** [Theme-Fusion/Localization-l10n#106]
Hello,

i've downloaded po file for de_DE. Poedit reported the file as corrupted, can't open it at all. Same happened to Avada.pot file. I uploaded .po and .mo files to languages/themes folder, but translations are not loading at all, even though i selected proper language in WP backend.

Is there some issue with these language files or am i doing something worng?

Regards

**Comment by mikka23** [comment]
How are you downloading the files?  It sounds like perhaps the problem is with the download method.

Please refer to here for more details - https://github.com/Theme-Fusion/Localization-l10n/issues/39#issuecomment-293206540

**Comment by tripatwhat** [comment]
You're right. Instead of downloading whole package, i was downloading only files i need, with right click -> save as. When i downloaded whole zip and unzipped it, everything worked well. I don't know why this matters, but obviously it does.

Thank you.

**Comment by mikka23** [comment]
For downloading individual files, if you use the raw link/button as described here https://github.com/Theme-Fusion/Localization-l10n/issues/70#issuecomment-372273193 it should work correctly.  I believe the other method causing problems particularly depending on the OS.
