### ISSUE TITLE
After save with poedit a lot of lines are deleted

### ISSUE THREAD

**Issue by m-behr** [Theme-Fusion/Localization-l10n#11]
Hi there,
i forked the project to adjust a german translation 'Load more posts' (working with POEdit). But if I try to create a pull request, git shows me that there are a lot of deleted lines (~ 300, starting with #~). 

I am not sure if this behaviour is correct, did i miss something ?

Thanks in advance,
Michael

**Comment by aristath** [comment]
Hey there!

That's ok, lines starting with # are just inline comments, they have no impact on the actual translations.
