### ISSUE TITLE
Title of theme mistranslated

### ISSUE THREAD

**Issue by kristoferaberg** [Theme-Fusion/Localization-l10n#114]
It seems there is something wrong with the translation of the title of the theme. On my site (with Swedish translation), it says the name of the theme is "Inaktivera Avadas stilar för Revolution Slider" rather than "Avada".

**Comment by aristath** [comment]
Hello @kristoferaberg,
Thank you for reporting this.
What should it say instead?
I see "Avadas" is used in a lot of places on that translation file, but my knowledge of Swedish is non-existent. I _assumed_ that the extra `s` was a locale thing

**Comment by loftreklam** [comment]
It should just say "Avada"... Now it says: "Inactivate Avada's styles for Revolution Slider", which is quite bananas...

**Comment by loftreklam** [comment]
There are plenty of words that are wrong in the Swedish translation. I guess you have made a automatic translation within Poedit. I have founded that the top suggestions there in many occasions are quite amusing, but absolutely not correct.

For instance, in Theme Options > Logotype, right at the bottom where the area should say "Mobile logotype" or something similar, in Swedish it says "Google maps"...

**Comment by loftreklam** [comment]
![screenprint themeoptions logotype](https://user-images.githubusercontent.com/49269706/67433164-f0efab00-f5e7-11e9-9211-5b07cb8ed65e.png)

**Comment by loftreklam** [comment]
![screenprint avada translation](https://user-images.githubusercontent.com/49269706/67433428-65c2e500-f5e8-11e9-8a98-48a3802d0a1b.png)

**Comment by aristath** [comment]
Hello @loftreklam,
Thank you for pointing these out! 👍 
We don't use automatic translations, our translations are community-driven. In other words, our users submit their translations, we review them for any obvious abusive content, spam messages etc, and if it seems OK the translations get merged.
If a member of our team speaks the submitted language then we can do a deeper review and check the correctness of the submitted translations.
As you can imagine we don't have a team member for every language - though we do cover a wide range.
Unfortunately none of us knows Swedish, so we can only do a "surface" check.

If you fix these errors and have updated translation files, we would be more than happy to merge your changes so the whole Swedish community can benefit.
You can submit an updated `.po` file via a pull-request in this repository, or even by sending an email to our support team and we can then manually merge them. 👍

**Comment by aristath** [comment]
Closing this issue, it was fixed by the updated translation files 4 days ago.
