### ISSUE TITLE
French for "Load more posts" not working

### ISSUE THREAD

**Issue by erthi16** [Theme-Fusion/Localization-l10n#123]
I've added translations for "Load more posts" both to the fusion-builder-fr_FR and fusion-builder-fr_CA.  Could you add them before the next update? 

Thanks you!

Eric Thibault

**Comment by aristath** [comment]
Hello @erthi16 

Where exactly did you add these translations? I was looking at pull-requests and submitted translations, I couldn't find anything from you.
Did you perhaps mean to upload files and they were not uploaded?

**Comment by erthi16** [comment]
Hello to you!

I was in the process of doing my pull request but was distracted by family matters… I’ll do that tonight.

Have a nice day

Éric Thibault
Chargé de programmation et d'analyse
Service des technologies de l’information et du soutien pédagogique
Faculté des sciences et de génie
Université Laval

T  418 656-2131, poste 418015

Avis relatif à la confidentialité<https://www.ulaval.ca/notre-universite/avis-de-confidentialite.html>

De : Aristeides Stathopoulos <notifications@github.com>
Envoyé : 28 octobre 2019 08:00
À : Theme-Fusion/Localization-l10n <Localization-l10n@noreply.github.com>
Cc : Éric Thibault <Eric.Thibault@fsg.ulaval.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Theme-Fusion/Localization-l10n] French for "Load more posts" not working (#123)

ATTENTION : L’émetteur de ce courriel est externe à l’Université Laval
Évitez de cliquer sur un hyperlien, d’ouvrir une pièce jointe ou de transmettre des informations si vous ne connaissez pas l’expéditeur du courriel. En cas de doute, contactez l’équipe de soutien informatique de votre unité ou hameconnage@ulaval.ca<mailto:hameconnage@ulaval.ca>.
________________________________


Hello @erthi16<https://github.com/erthi16>

Where exactly did you add these translations? I was looking at pull-requests and submitted translations, I couldn't find anything from you.
Did you perhaps mean to upload files and they were not uploaded?

**Comment by erthi16** [comment]
Pull request submitted... It is my first so... hoping it is OK!

**Comment by aristath** [comment]
Everything was great! Thank you 👍 

Closing this ticket since it was fixed via #131
