### ISSUE TITLE
Dutch BE translation + addition

### ISSUE THREAD

**Issue by MabadosS** [Theme-Fusion/Localization-l10n#150]
Hi,

1) 
It seems dutch BE is not translated. Dutch NL is the same language as Dutch BE. Maybe someone can copy the DUTCH NL translation into the dutch BE translation.

I dit it manualy for my websites but it would be easier if the Dutch BE translation already has the content.

2)
In the dutch NL translation (fusion-builder-nl_NL, fusion-core-nl_NL) the text 'Load more posts' is not translated. Can someone add the translation 'Meer laden'

**Comment by ilicfilip** [comment]
Hello @MabadosS ,

1. I've just checked our language files and I can see nl_BE translation file for [Avada](https://github.com/Theme-Fusion/Localization-l10n/blob/master/Avada/Avada-nl_BE.po), [Fusion Core](https://github.com/Theme-Fusion/Localization-l10n/blob/master/fusion-core/fusion-core-nl_BE.po) and [Fusion Builder](https://github.com/Theme-Fusion/Localization-l10n/blob/master/fusion-builder/fusion-builder-nl_BE.po). Can you please check it again on your side?

2. I've added translation for "Load More Posts" for both nl_NL and nl_BE translation files, recompiled them and new translation files should be available already.

**Comment by MabadosS** [comment]
> Hello @MabadosS ,
> 
> 1. I've just checked our language files and I can see nl_BE translation file for [Avada](https://github.com/Theme-Fusion/Localization-l10n/blob/master/Avada/Avada-nl_BE.po), [Fusion Core](https://github.com/Theme-Fusion/Localization-l10n/blob/master/fusion-core/fusion-core-nl_BE.po) and [Fusion Builder](https://github.com/Theme-Fusion/Localization-l10n/blob/master/fusion-builder/fusion-builder-nl_BE.po). Can you please check it again on your side?
> 2. I've added translation for "Load More Posts" for both nl_NL and nl_BE translation files, recompiled them and new translation files should be available already.

Hi,

1) Yes the language files are present, but they do not contain any translation. Just the English lines are present in the language files of nl_BE. Only one line is translate now, because you added the translation of 'Load more posts'. Thats why I suggested to copy the content of the nl_NL file into the nl_BE file. Our languages are identical.

2) Thanks

**Comment by ilicfilip** [comment]
Hey @MabadosS ,

1. You're right. I've checked nl_BE language files and they were completely empty, so I replaced them with current nl_NL files and updated files are already available.

Can you tell me if I can do the same with other Dutch language variation? For example nl_NL_formal?

**Comment by MabadosS** [comment]
Thank you.

Yes you can do the same with nl_NL_formal . We speak all the same language ;-) Only different country.

**Comment by ilicfilip** [comment]
Done, nl_NL_formal translations are already available.

@MabadosS , thank you for you contribution!
