### ISSUE TITLE
Avada-nl_NL translation files from Dylan / Yuluma

### ISSUE THREAD

**Issue by mabbas64** [Theme-Fusion/Localization-l10n#152]
This came through the support area from:
Dylan
Yuluma

[Attachments.zip](https://github.com/Theme-Fusion/Localization-l10n/files/4093533/Attachments.zip)

Ref tick # 314080

**Comment by maximus80** [comment]
updated our repo.

**Comment by aristath** [comment]
API updated to include the updated translations.
