### ISSUE TITLE
Why Arabic language is not supported?

### ISSUE THREAD

**Issue by khaledsawwaf** [Theme-Fusion/Localization-l10n#16]
This accounts for 5.2% of the world's population.
By Published Sunday, October 30, 2011.
The combined population of the Arab countries totalled around 367 million this month, nearly 5.2 per cent of the world's population, official data showed. :)

could you please support it? because i bought this theme thinking of that all translation languages are supported, but i was shocked that Arabic is not there :S

**Comment by m1chelangel0** [comment]
Hi @khaledsawwaf 

We absolutely 100% would love to have a 100% complete set of Arabic language files for Avada. The issue for us is that we rely on our customer base to contribute to completing the language files that we include with Avada and unfortunately do not have an Arabic fluent staff member to help us out with this.

If you would be interested in contributing toward completing a set of Arabic language files for Avada, it would be a fantastic service to our customer base as a whole

Thank you kindly

**Comment by khaledsawwaf** [comment]
Did you start with that project before? do you have any previous data? or should i start from the beginning?

**Comment by aristath** [comment]
@khaledsawwaf hello there!

> Did you start with that project before? do you have any previous data? or should i start from the beginning?

From what I can see nobody has contributed any Arabic translations so far, so you'd have to start from the beginning...

Translations don't have to be complete, if you want to start contributing slowly by translating a few strings every now and then this may also motivate others to start contributing as well! 👍

**Comment by khaledsawwaf** [comment]
Hello,
I made some translation for Arabic, where should i upload it so that this translations will be used automatically with Avada users in future plans?

**Comment by aristath** [comment]
Hello again @khaledsawwaf 
Ideally you can create a pull-request on this repository.
If you don't know how to do that, you can simply upload your files by attaching them on your reply on https://github.com/Theme-Fusion/Localization-l10n/issues/16 and we'll take care of the rest. 👍

**Comment by khaledsawwaf** [comment]
i made a pull-request, see you in next version 👍 
Regards.

**Comment by lukeabeck** [comment]
Thanks @khaledsawwaf !

**Comment by aristath** [comment]
Closing this one as it was merged on Dec.15 👍
