### ISSUE TITLE
Avada-sv_SE translation file from a customer

### ISSUE THREAD

**Issue by sohaibmuzammal786** [Theme-Fusion/Localization-l10n#160]
Customer says they have fixed some mistakes in the language file.

ref ticket : https://secure.helpscout.net/conversation/1085891573/318609?folderId=485908

[Avada-sv_SE.po.zip](https://github.com/Theme-Fusion/Localization-l10n/files/4228971/Avada-sv_SE.po.zip)

**Comment by maximus80** [comment]
updated.

**Comment by aristath** [comment]
API updated
