### ISSUE TITLE
Align terminology with WooCommerce translation file for 'Kortingsbon' in stead of 'Coupon'

### ISSUE THREAD

**Issue by yulumadavid** [Theme-Fusion/Localization-l10n#162]
WooCommerce uses the terminology 'Kortingsbon' and 'Kortingsbon code' when it comes to 'Coupon' and 'Coupon code'. Therefore I believe that Avada should follow that terminology to align the translation.
[Avada-nl_NL.zip](https://github.com/Theme-Fusion/Localization-l10n/files/4410637/Avada-nl_NL.zip)

**Comment by aristath** [comment]
Hello @yulumadavid, thank you for your translations!

I just pushed these changes so I'll go ahead and close this thread.
However, the files included in your zip file were changing the format of all strings so I had to manually review and apply your changes instead.
You can see the changes in [this commit](https://github.com/Theme-Fusion/Localization-l10n/commit/581330731e0f3161a0331ac887116c08827e3d32), so if you see something missing please let me know so we can add it. :+1:

**Comment by yulumadavid** [comment]
Looks perfect
