### ISSUE TITLE
Translation files from gcPhil / ThoMarketing

### ISSUE THREAD

**Issue by gcPhil** [Theme-Fusion/Localization-l10n#164]
Please find my updated translation files attached. I added some missing German translations.

Avada-de_DE
fusion-builder-de_DE
fusion-core-de_DE

[Attachments.zip](https://github.com/Theme-Fusion/Localization-l10n/files/4545741/Attachments.zip)

**Comment by aristath** [comment]
Thank you @gcPhil :)

Your translations were merged and the API updated to include the new strings.
