### ISSUE TITLE
Advanced translation tool

### ISSUE THREAD

**Issue by miloshavlicek** [Theme-Fusion/Localization-l10n#170]
Hi, I have a suggestion.

**Proposed solution:**
- **Use an online advanced translation tool** to do the translation process friendlier for non-technical users. It would be also possible to translate without need of any additional software and from any device since it could work online.
- I propose to use [Weblate](https://weblate.org/), it is an open-source project and it can be self-hosted. One of the easiest solution to host it is to use AWS: https://aws.amazon.com/marketplace/pp/Bitnami-Weblate-Certified-by-Bitnami/B00NN8X6U2

If you will be interested, I can help you with the implementation.

**Comment by mikka23** [comment]
Thanks for the suggestion Milos.  We have had an item on our main list for looking for better ways to manage translation.  I'll add the Weblate service to our item regarding that 👍

**Comment by miloshavlicek** [comment]
@mikka23 Weblate is tightly integrated with GIT, so it would be relatively easy to implement (including reviews etc.) it to this repository and the same workflow can "remain" (ideally with CI as suggested in #171). The only change would be that this repository would be read-only for translation files, however, README can contain some useful information how to contribute and on which URL can be the translation tool found.
