### ISSUE TITLE
Issue with German Translation

### ISSUE THREAD

**Issue by lukeabeck** [Theme-Fusion/Localization-l10n#18]
A customer on FB likes the udpate but says she always has to redo German translations.  See comments below.  @maximus80 I tagged you in it since you speak German :)

--------------------------------------------------------------------------------------

_Hi, everything's fine. Still, what is not so lucky are the "german translations". I still have to change translations manually._

_There are five words. Under each blog post there is "by, categories, tags, comments". I don't know why, but I have to change by, categories and comments in avada-functions. Comments however is correct in the german word "Kommentare". The second change I do is in the file comments. There I have to change the words "logged in as , Logout" into "Angemeldet als , Abmelden". That's is. All the rest is in German. The language files seem to be actual. I installed out of Wordpress , so I did not load down anything. Do you know what I mean? Best, Ulrike Winzer_

**Comment by maximus80** [comment]
None of these strings is translated in the German mo file, but the strings are all registered there. So I guess she just doesn't know how translations work.
I have added these translations, so they will be available in next version.

**Comment by ulrikewinzer** [comment]
Hi, just updated to version 5.02 and the englisch wording is there again: By, categories, tags
What do I do wrong? Best, Ulrike
![englisch](https://cloud.githubusercontent.com/assets/19272560/19527182/59283e5e-9627-11e6-845d-6d107bfd6246.png)
