### ISSUE TITLE
Translate "You have $s items..." in woocommerce cart page to spanish

### ISSUE THREAD

**Issue by lamia51** [Theme-Fusion/Localization-l10n#180]
It's done
[Avada-es_ES.zip](https://github.com/Theme-Fusion/Localization-l10n/files/4736602/Avada-es_ES.zip)

**Comment by aristath** [comment]
Hello @lamia51 
Just a few minutes ago we merged another update for Avada-es_ES, and among other translations it included one for this too, so I'll go ahead and close this ticket.
Thank you for contributing to our community! :heart:
