### ISSUE TITLE
Getting an issue after updating to 5.0.2

### ISSUE THREAD

**Issue by blmg911** [Theme-Fusion/Localization-l10n#19]
Fatal error: Call to undefined function avada_is_portfolio_template() in /wp-content/plugins/fusion-builder/shortcodes/fusion-container.php on line 299

**Comment by lukeabeck** [comment]
Hello @blmg911 

This is a public repo for localization only. For theme support, please signup at our support center and submit a ticket, you can do so by following these steps: http://theme-fusion.com/support-ticket/

Our support team will gladly help you out there.

Thanks!
