### ISSUE TITLE
Avada theme zh_TW language

### ISSUE THREAD

**Issue by snoopy75824** [Theme-Fusion/Localization-l10n#192]
hello
I want to provide the revised zh_TW language file.
Let future versions of zh_TW see the correct translation.
There are many incorrect translations in the current zh_TW file.
I have fixed those errors.
[avada-zh_TW.zip](https://github.com/Theme-Fusion/Localization-l10n/files/5426719/avada-zh_TW.zip)

**Comment by maximus80** [comment]
Thanks for your contribution, your translations have been merged in.
