### ISSUE TITLE
Improve link in a string

### ISSUE THREAD

**Issue by Ter747474** [Theme-Fusion/Localization-l10n#197]
Hi,
 I'm not really sure if the last link in this string:

`#: includes/admin-screens/support.php:22
msgid ""
"Avada comes with 6 months of free support for every license you purchase. "
"Support can be <a %1$s>extended through subscription</a> via ThemeForest. To "
"access Avada support, you must first setup an account by <a %2$s>following "
"these steps</a>. If you purchased Avada through Envato's guest checkout, <a "
"%3$s>please view this link</a> to create an Envato account so you can "
"receive support."`

which leads only to EnvatoMarketHelp front page is the best possible one ???

I can't test it but I would assume that if a person follows that link and creates a new account (possibly with a different email), he would have a hard time to link his "guest-purchased-license" to his new account, which would possibly lead to numerous, unnecessary customer service contacts.

It says elsewhere:

"How do guests claim their Envato account?
The order confirmation email for all guest purchases contains a link to claim their full Envato account."
https://forums.envato.com/t/guest-checkout-on-envato-market/91922

Sincerely
Tero

**Comment by maximus80** [comment]
Hello Tero,

Envato has abandoned guest checkout, which is, why the link is no longer correct and also why we will update that section in an upcoming release.

Thanks!
