### ISSUE TITLE
Rename Avada Translation files

### ISSUE THREAD

**Issue by hassan-tariq** [Theme-Fusion/Localization-l10n#20]
Rename Avada Translation files properly like Avada-es_ES.po instead of es_ES.po because each time we have an update, need to download the files again and rename them all.

**Comment by lukeabeck** [comment]
So for 503 I just need to download the new zip from this repo and replace the language files from current 502 package?

**Comment by aristath** [comment]
Yup!

It was a simple fix, just had to rename the files and make sure our automation script uses the new filenames. 👍

**Comment by lukeabeck** [comment]
Nice, thanks buddy :)
