### ISSUE TITLE
Amazing free contributors !

### ISSUE THREAD

**Issue by huberte** [Theme-Fusion/Localization-l10n#202]
I tried to explain to both Avada and Envato that you cannot rely on "amazing contributors" for tranlating more than 7000 lines. They don't care. I didnt want to be paid, but even a licence was to "expansive" for them :/

Let's just take a look of the 5th most spoken language and its translation.

fusion-builder : 4865 untranslated, latest translation 2019, plus two errors (éffacer and restorer :| )
fusion-core : 503 untranslated, latest translation 2017
avada : 3294 untranslated lines, latest tranbslation 2018;, a lot of errors

I did a lot of pre translation, thanks to a pro poedit licence (which I pay), and surely should be revisited. I did a lot of correction too.

**Comment by mikka23** [comment]
Regarding a license giveaway, that is something we (ThemeFusion) are not allowed to do due to the marketplace terms and conditions, otherwise we would.  In terms of trying to improve the translations, that is something we are already looking into.
