### ISSUE TITLE
Translated file cannot be found

### ISSUE THREAD

**Issue by IgorIlgiyaev** [Theme-Fusion/Localization-l10n#206]
Hey
I have made almost 130 string translation and wanted to continue translating but now as I get in its not there....

**Comment by maximus80** [comment]
Hey,

Can you give us some more details? I guess you are referring to a local translation update? Maybe folder structure of your install is incorrect, i.e. you have an older file in a place that takes precedence?

**Comment by IgorIlgiyaev** [comment]
I have translated the Fusion Builder folder and not the Avada folder. I have looked in my repository and still didn’t saw it.

**Comment by maximus80** [comment]
Where do you usually store your translation files?

**Comment by IgorIlgiyaev** [comment]
As usual I click the raw pencil and edited through GitHub and saved.

**Comment by maximus80** [comment]
So, you have edited the translation files on your own private GitHub repo, right? Or did you try directly on this repo?

**Comment by IgorIlgiyaev** [comment]
Directly

**Comment by maximus80** [comment]
On this repo, you can only add changes as a PR, so direct file editing and uploading is not possible.
Unfortunately, I also can't see any activity on the repo in the Fusion Builder folder. So, as bad as it sounds, I'm afraid your changes have not been saved, sorry.

In general, we do recommend doing the changes locally on your install and then push them as a PR here, which ensures nothing can get lost.

**Comment by IgorIlgiyaev** [comment]
I did this last time and it saved perfectly

**Comment by maximus80** [comment]
That would be strange indeed, as the repo has always been public, but not directly writeable. In any case, sorry for the inconvenience!

**Comment by IgorIlgiyaev** [comment]
So basically I did a wasted job? Let’s say if I want to do that again and not loose all the data?

**Comment by maximus80** [comment]
Looks like this is your commit: https://github.com/IgorIlgiyaev/Localization-l10n/commit/de26abc96d35d2586d15735c1edf6d0d86a43d1f?
If so, that is on a forked repo from our langs one: https://github.com/IgorIlgiyaev/Localization-l10n

You can create a PR of that commit, and we can then merge it in, so no work was lost 😃

**Comment by IgorIlgiyaev** [comment]
Can you upvote me for translations so i can do it directly from the repo?

**Comment by maximus80** [comment]
Direct editing on the main repo isn't a good idea, unfortunately. In general, doing PRs it is a lot easier for us to see any merge conflicts or other issues, that could not be easily seen when editing directly.
So, moving forward, we either suggest doing the changes on your fork and then creating a PR, or doing the changes locally through an editor, which would be simpler for you to do, and then create a new PR on our main repo, for us to merge the changed files in.

Thanks for your work and your contributions!

**Comment by IgorIlgiyaev** [comment]
Creating a PR? Sorry not that savvy in Github :-)

**Comment by ilicfilip** [comment]
Hello @IgorIlgiyaev ,

What you've done was actually harder part :)

[You created a 'fork'](https://github.com/IgorIlgiyaev/Localization-l10n) (copy of our Localization repository on your own Github account): https://prnt.sc/xz1jow

There you can notice that there are several branches created, your latest change is on 'patch-7' branch. You just need to select it and then click on "Pull Request" on the right: https://prnt.sc/xz1qde

Last step would be just to enter a Title and Description and click 'Create Pull Request': https://prnt.sc/xz1stj

**Comment by IgorIlgiyaev** [comment]
Check if I did that correctly :-)

**Comment by ilicfilip** [comment]
You did, PR merged :)

Thank you!

**Comment by IgorIlgiyaev** [comment]
Awesome just saw the email :-) Learned something new with the Master dropdown and found the translated strings :-)
