### ISSUE TITLE
No translation appearing

### ISSUE THREAD

**Issue by huberte** [Theme-Fusion/Localization-l10n#208]
Hi, I Just did translate almost 8000 lignes but translation is not apperaing.

I followed this : https://theme-fusion.com/documentation/avada/translations/included-language-files/

Could you check please ?

**Comment by mikka23** [comment]
For which product, Avada, fusion-builder, fusion-core?  You previous changes were actually merged in earlier this week https://github.com/Theme-Fusion/Localization-l10n/commit/9e5c906e780e75f4494fb9c8e46dfa5b1d0605e3#diff-f2d7f8cb67839c4aa636cf87fd0ca3cd40ee970d96a31f4dc1d68d07c0e5ff28.

**Comment by mikka23** [comment]
Checking now, how did you edit the files?  That particular french edit has 640 errors due to duplicates.

**Comment by mikka23** [comment]
I have had to revert the Avada file back because those changes were not valid.

**Comment by huberte** [comment]
I used poedit pro, let me check again those files. 

No translation appear, avada, core or fusion. 

Could you be more specific on errors or fuzzy ?

**Comment by huberte** [comment]
Avada file :

* Traduction                                         Éléments                 Mots           Caractères
Traduit                                              93 (2 %)                  303                 1838
À réviser                                         4865 (98 %)                35580               220300
Traductions avec erreurs                                    0

 *Texte source
Chaînes dans la langue source                            4958                29661               173623
À réviser                                                                    29412               172204
Non traduit                                                 0                    0                    0

How did you found errors, how did you edit the files ? 

Let us check file by file if you agree

**Comment by mikka23** [comment]
Hi, the errors are due to duplicate entries.  Eg check here: https://github.com/Theme-Fusion/Localization-l10n/blob/9e5c906e780e75f4494fb9c8e46dfa5b1d0605e3/Avada/Avada-fr_FR.po.  I already reverted the file though.  So if you are checking on the repo version the errors were removed.

Search for - **Header Social Icons Styling**.  The file contains two translations in different parts of the file for the same thing.  That breaks the file in poedit.

Fuzzy translation is a flag for translations https://poeditor.com/kb/fuzzy-translations.  Usually if they are labelled fuzzy it means they were some kind of auto translate.  It doesn't change how its used but if the translation is known to be accurate then its best not to be labelled fuzzy for any future translations.

**Comment by huberte** [comment]
Hi, 
On avada : I checked my previous file and the line you mentioned does appear just once. 

```
#: includes/options/social_media.php:194
#, fuzzy
msgid "Header Social Icons Styling"
msgstr "Style des icônes sociales d'en-tête"
```
Thing is I had to correct about 20 translations because we have a lot of english typo "errors" ( point and white space at end, or white space at the beginning)

Let me send the avada file again and we could discuss it there ? I did re read somme fuzzy, but again as I said to avada theme and envato, I will not reread 8000 lines for free. Sorry. 

IMHO, those lines will be "defuzzed" when soemone see an error (there is no big error though)

**Comment by huberte** [comment]
OK, so there should be no reason that my translaiton does not appear. But still in english

**Comment by mikka23** [comment]
Correct, with that latest file they should be working.

**Comment by huberte** [comment]
Here the first item for ava option 


Mise en page 
Controls the site layout. | Encadré Large

 
Largeur du site
Controls the overall site width. Enter value including any valid CSS unit, ex: 1200px.

**Comment by mikka23** [comment]
That will be due to the fuzzy flag.  I did not realise that but fuzzy translations are not used until confirmed and fuzzy flag removed.  You can test by editing that string and setting fuzzy off.

**Comment by huberte** [comment]
OK? there were some error on non fuzzy translation though . I did correct them and remove fuzzy flag. I will update the three files

**Comment by huberte** [comment]
It work ! Thanks !
