### ISSUE TITLE
' character 

### ISSUE THREAD

**Issue by huberte** [Theme-Fusion/Localization-l10n#214]
Sorry again :(

I have an issue with my '

```
#: shortcodes/fusion-user-login.php:1530
msgid "User Register"
msgstr "Inscription de l'utilisateur"
```

show as :
Inscription de l&#039;utilisateur

I did search po file database, but I don't see anything

**Comment by mikka23** [comment]
Referring to the fact its encoded in the builder? If so that will have to change in the plugin and is not the fault of the translation.

**Comment by huberte** [comment]
Ha, o ,do you say that to avada then ?

**Comment by mikka23** [comment]
For the second part, yeah that is what I was referring.

For for the first question, what do you mean?  You mean, will I tell developers of Avada to fix it?  If so, I am a developer for Avada and have added a fix which will be part of the next release.

**Comment by huberte** [comment]
Hi mikka23, any news about the bifg work I did with translation ? Did you speak with the Avada team ? Couls we speak via mp ?

Thanks.
