### ISSUE TITLE
Avada & FC Spanish translations

### ISSUE THREAD

**Issue by m1chelangel0** [Theme-Fusion/Localization-l10n#22]
Provided to us by a customer, attached here

[Avada_spanish_translate.zip](https://github.com/Theme-Fusion/Localization-l10n/files/575178/Avada_spanish_translate.zip)
[fusion-core-spanish-translate.zip](https://github.com/Theme-Fusion/Localization-l10n/files/575179/fusion-core-spanish-translate.zip)

**Comment by aristath** [comment]
fixed
