### ISSUE TITLE
Wordpress error with fusion-builder-nl_NL

### ISSUE THREAD

**Issue by pretfred** [Theme-Fusion/Localization-l10n#226]
When I upload the translation of fusion-builder the backend of site goes in error when updating a post. When I delete the translation the backend is back.

**Comment by mikka23** [comment]
Hi,  I am unable to replicate a problem with those files.  If it fails when updating it sounds like it could be a memory issue, or caused by yoast content analysis.  Please turn on `wp_debug` and post the error you receive.  It will provide more information about what is going on.

Thanks
