### ISSUE TITLE
String not translatable

### ISSUE THREAD

**Issue by aurelienpierre** [Theme-Fusion/Localization-l10n#23]
_"Like This Post? Share It With Others!"_ displayed in the social sharer on posts and portfolios is not translatable since it does not appear in the `avada.pot` file.

**Comment by lukeabeck** [comment]
Hello!

I assume you are referring to the social share box that sits below blog posts and portfolio posts?  You can translate it in theme options: http://d.pr/i/oFg5

**Comment by aurelienpierre** [comment]
Oh ok, sorry. This should be a recent change, I never saw it.

**Comment by lukeabeck** [comment]
No problem :)
