### ISSUE TITLE
translate/change post elements 

### ISSUE THREAD

**Issue by zamantech** [Theme-Fusion/Localization-l10n#241]
Hello,
how is possible to translate/chnage meta data,related post ?
i try to change them but no luck
like :
- Related posts Element
![image](https://user-images.githubusercontent.com/64734686/206898000-09b30800-eaa2-4927-96c9-b69bf2f825fd.png)
i was unable to change related post and comments
- Meta Element
![image](https://user-images.githubusercontent.com/64734686/206898114-292ffe7a-201e-48f6-811d-21c2f510fe71.png)
like By,Last updated etc..
- Author Element 
![image](https://user-images.githubusercontent.com/64734686/206898194-2fd54b48-71de-4b76-8919-96a2c49d3d24.png)
etc..
so are there way to edit them?
Best Regards

**Comment by maximus80** [comment]
Hello,

these strings come from WordPress itself, so you will have to change the language in Settings > General > Site Language.
