### ISSUE TITLE
Blog comment form translations not taking effect.

### ISSUE THREAD

**Issue by Ter747474** [Theme-Fusion/Localization-l10n#251]
One of my sites uses Avada Magazine theme. The site is up-to-date.
Correct translations can be located in the Avada-fi.po file.
All other translations are displaying correctly, but blog comment strings remain in English. No changes has been made to the blog comment form.

**Comment by maximus80** [comment]
It depends a bit on which comment strings exactly you are referring to. The Magazine prebuilt uses the comments element and that is translated through the fusion-builder.po files. So, please give that a try.

**Comment by Ter747474** [comment]
That fixed it. 
I had already translated these in the fusion-builder.po few Avada updates ago.
Now I had to manually insert the files to make it work, even though I have the automatic updates turned on.

**Comment by maximus80** [comment]
It might be missing in the fusion-builder.po file of your language then. You can create a pull request with your updated local file here, and then we can merge that in, so that you don't have to manually do it in the future.

**Comment by Ter747474** [comment]
No, that's probably not it. My fork is in sync with your project.
When I look into your fusion-builder folder and look up the fusion-builder-fi.po file I can see that my contributions are already there between lines 19225-19281.

**Comment by maximus80** [comment]
Then you should be able to obtain the correct and latest file from our repo.
