### ISSUE TITLE
Dutch translation for 'Update' is not 'Afrekenen'

### ISSUE THREAD

**Issue by xenonis** [Theme-Fusion/Localization-l10n#28]
Hi,

If you update Avada, the [Update] button for plugins says [Afrekenen] in Dutch (nl_nl), that's wrong (it means settle a bill). In Dutch it can either stay [Update] or translated to [Bijwerken] (which is the WordPress translation for updating plugins).

I don't know how to contribute to the translations here, so that way I do it this way.

**Comment by aristath** [comment]
Thanks! fixed 👍

**Comment by xenonis** [comment]
That's quick, thanks!
