### ISSUE TITLE
Translation for Count Down Timer not working

### ISSUE THREAD

**Issue by hassan-tariq** [Theme-Fusion/Localization-l10n#29]
Tried with the fresh files but the translation for the Weeks, Days, Hrs, Min and Sec isn't working.

**Comment by lukeabeck** [comment]
@hassan-tariq this one was closed out, is it good or still needs fixed?

**Comment by tmtben** [comment]
It still needs fixed.
Does not work for fr_FR.

**Comment by hassan-tariq** [comment]
Sorry, guys its all good already. It was my cache issue.

**Comment by tmtben** [comment]
For me, the translation for the Weeks, Days, Hrs, Min and Sec isn't working.
Tried fr_FR and de_DE.

**Comment by hassan-tariq** [comment]
@tmtben  Please open a ticket with us including login access details and we'll check it -> https://theme-fusion.com/support-ticket/

**Comment by mikka23** [comment]
Please make sure you are checking in the Fusion Builder language files and that they are translated in two places.

You will find - %s Weeks
Also just - Weeks

The one used on the front-end, is Weeks.

**Comment by tmtben** [comment]
> Note, a translation hasn't been added into the files yet, but the strings are present and available to be translated.

Yes, I've added my own strings instead of the empty ones. But the default strings (the english ones) are still displayed.

**Comment by mikka23** [comment]
Hi tmtben,

For both the string versions?  So both %s Weeks and Weeks?

**Comment by tmtben** [comment]
> For both the string versions? So both %s Weeks and Weeks?

Yes, here are my changes:

#: js/previews/fusion-countdown-preview.php:50
msgid "%s Weeks"
msgstr "%s Sem."

#: js/previews/fusion-countdown-preview.php:53
msgid "%s Days"
msgstr "%s j"

#: js/previews/fusion-countdown-preview.php:54
msgid "%s Hrs"
msgstr "%s H"

#: js/previews/fusion-countdown-preview.php:55
msgid "%s Min"
msgstr "%s M"

#: js/previews/fusion-countdown-preview.php:56
msgid "%s Sec"
msgstr "%s S"

#: shortcodes/fusion-countdown.php:106 shortcodes/fusion-countdown.php:107
msgid "Weeks"
msgstr "Semaines"

#: shortcodes/fusion-countdown.php:112 shortcodes/fusion-countdown.php:113
msgid "Days"
msgstr "Jours"

#: shortcodes/fusion-countdown.php:118
msgid "Hrs"
msgstr "H"

#: shortcodes/fusion-countdown.php:119
msgid "Hours"
msgstr "Heures"

#: shortcodes/fusion-countdown.php:124
msgid "Min"
msgstr "M"

#: shortcodes/fusion-countdown.php:125
msgid "Minutes"
msgstr "Minutes"

#: shortcodes/fusion-countdown.php:130
msgid "Sec"
msgstr "S"

#: shortcodes/fusion-countdown.php:131
msgid "Seconds"
msgstr "Secondes"
