### ISSUE TITLE
Theme Name Translation for German Language.

### ISSUE THREAD

**Issue by hassan-tariq** [Theme-Fusion/Localization-l10n#31]
I have seen it many times. The theme name is like this when you use German Translation files so likely a string is wrongly translated --> https://theme-fusion.com/index.php?gf-download=2016%2F12%2Fms%40so-systics.de-1480765075.jpg&form-id=6&field-id=10&hash=84b6320338e2f1b679b305066a41e166f07669e647af6d48e3d39334ec4c9978

**Comment by lukeabeck** [comment]
This recalls a deep memory, from far far away .... that I could not find on Git 💃

**Comment by aristath** [comment]
I can't think of anything in the theme that would cause this....

**Comment by lukeabeck** [comment]
@maximus80 any recollection?

**Comment by maximus80** [comment]
This seems very weird and is not happening on my install.

I have also updated quite a few strings for German files in last version, so we should be good here.

**Comment by hassan-tariq** [comment]
Here is the screenshot of what I see currently translated for 505 unless you changed its translation above :D

![2016-12-14_1553](https://cloud.githubusercontent.com/assets/5371053/21179351/7cfcbfa2-c215-11e6-98db-e7f6b7eba7f7.png)

**Comment by mikka23** [comment]
Yeah, this has existed for a long time.

**Comment by aristath** [comment]
Fixed

**Comment by maximus80** [comment]
hm obviously I did not push that to lang repo, weird.
Updated second string as well.

**Comment by maximus80** [comment]
Although his is still weird, as these strings shouldn't even be used there, as they are accessed from the data object. Very weird indeed.

**Comment by aristath** [comment]
Yeah, it was weird... In any case though it should be ok now 👍

**Comment by lukeabeck** [comment]
Meh, I did not include new lang repo in 506 that is currently being reviewed.
