### ISSUE TITLE
Fusion-builder files are not translated

### ISSUE THREAD

**Issue by lilalou77** [Theme-Fusion/Localization-l10n#33]
Hello, 
I need to translate the fusion builder in french but the files are not translated and it seems to be the same for the other languages, all is always in english... 
Can you help me ?

**Comment by m1chelangel0** [comment]
Hi there

Thank you for contacting us

As this is not our official support channel, I suggest creating a support ticket here -> https://theme-fusion.com/support/ - and our support will be glad to assist and guide you

How to register for support -> https://theme-fusion.com/avada-doc/getting-started/avada-theme-support

Thank you kindly

**Comment by lukeabeck** [comment]
Hello,

Fusion Builder is translatable, the files are in the main download package and you'l see a folder like this: http://d.pr/i/7a6k

You can download them from this repo link (click download button): https://github.com/Theme-Fusion/Localization-l10n

Or get them in the main package from Themeforest on your Downloads page.
