### ISSUE TITLE
Security concern: translator emails are publicly visible from this repository.

### ISSUE THREAD

**Issue by aristath** [Theme-Fusion/Localization-l10n#38]
A user complained that they get spammed because their email is visible in our translation files and requested that we remove their email address.

email addresses are added by poEdit when the user translates the file, and then if they submit the translation file without deleting it themselves the email is automatically merged.
However a couple of years ago we were using transifex so a few email addresses are still preset here from that time.

In the future if a translator doesn't want their email to be publicly available then ideally they would just delete their email from the `.po` file before submitting it to this repository.

We should go through all translation files and remove all translator emails references.

**Comment by aristath** [comment]
all email references were removed from our translation files.

**Comment by lukeabeck** [comment]
Thanks @aristath 👍
