### ISSUE TITLE
Poedit 

### ISSUE THREAD

**Issue by macg11** [Theme-Fusion/Localization-l10n#39]
I was wondering why can't I open any of po files in the latest poedit?
It says the file is not valid or corrupted po file.
It seems like they are working just fine when uploaded on the server but I need to edit them further.

**Comment by aristath** [comment]
Hello there!

I just tested all Avada translation files using Poedit 1.8.12 and  I could not replicate your issue.. I also asked 2 other team members to test this and they did not encounter any issues either.

Which file are you trying to open?

**Comment by macg11** [comment]
I am using Poedit 1.8.12 trying to open files:
Avada-pl_PL.po, fusion-builder-pl_PL.po and fusion-core-pl_PL

**Comment by aristath** [comment]
@macg11 I opened those files fine on my machine...
I then re-saved them using latest Poedit and re-uploaded them.

Can you please test if those new files work for you?

**Comment by aristath** [comment]
@macg11 any update on this one? Were you able to use the latest files?

**Comment by macg11** [comment]
No.. Still nothing. I have installed Poedit on another computer.. Tried a beta version as well... Same error..

**Comment by zagcom** [comment]
Hi,

same problem here. I tried to open files with older versions on poedit, but there is still the same statement: "the file may be corrupted or unrecognizable by Poedit".

Same statement was while I tried to check fr_FR file.

**Comment by lukeabeck** [comment]
@Theme-Fusion/developers any idea what is going wrong here?

@zagcom  and @macg11 can you make a short video of exactly what you are doing? Also provide the version of POEdit you are using and operating system.

Thanks!

**Comment by sulmanpucit** [comment]
I have checked on Mac. File is opening absolutely fine in 1.8.12 for me -> http://prntscr.com/emo1py

@macg11 @zagcom You are on Windows or Mac?

**Comment by macg11** [comment]
I am on Win 8.1

>> http://prnt.sc/emo5a5

**Comment by lukeabeck** [comment]
Would it make a difference that in your shots @macg11 do not show the file extension>

For example, there is no .po http://d.pr/i/ztA9

**Comment by zagcom** [comment]
In Windows by the default files extensions are hidden.

My screen: http://prnt.sc/emsxwl  (sorry but system in polish)

I am using Windows10 and Poedit version 1.8.12

**Comment by lukeabeck** [comment]
Very strange, we're trying to replicate but cannot so far.

@Theme-Fusion/developers @Theme-Fusion/support anyone with Windows10 and Poedit version 1.8.12 please try to replciate

**Comment by aristath** [comment]
The only reason I can think of that would cause this is if for some reason it opens the .mo file instead of the .po file.
In that case it would definitely not be able to recognize it.

**Comment by macg11** [comment]
I don't have the .mo file in the folder.. it is just the .po file..

**Comment by alexander-zimmermann** [comment]
Folks,

how you download the files? If I use wget to pull a file I encounter the same issue. If I download the full zip file, no issue. Strange.

**Comment by aristath** [comment]
> If I use wget to pull a file I encounter the same issue.

I've tried by downloading the zip file, and also using `git clone` to get this repository on my localhost.
If you get this URL using wget it will fail: https://github.com/Theme-Fusion/Localization-l10n/blob/master/Avada/Avada.pot
and this is the correct one: https://raw.githubusercontent.com/Theme-Fusion/Localization-l10n/master/Avada/Avada.pot
However, depending on your system's configuration perhaps the line-ends are converted to windows format and poedit can't see them properly after that?
In any case, downloading the zip file is the safest method.

**Comment by hassan-tariq** [comment]
Checked in Windows 10 with PoEdit 2.0 version and the Translation files are opening fine. 

![2017-04-07_1929](https://cloud.githubusercontent.com/assets/5371053/24804640/824d663e-1bc8-11e7-8569-09282c4cc1ed.png)

**Comment by lukeabeck** [comment]
Had another report from a user in comments today about this. I've asked them to post here with more information.

**Comment by Alexey666** [comment]
Win 10 / poedit 2.0 (and I tried different system win 7) situation remaining the same. The file without translation. But if I translate a few words then upload to my site it shows just translated on my own.
(Hope you understand my poor English)
So I would be happy if you could send me those two files (translated)  info.dokaf@gmail.com

**Comment by Alexey666** [comment]
I need fusion-builder-ru_RU.mo fusion-builder-ru_RU.ro translated into russian

**Comment by lukeabeck** [comment]
@Theme-Fusion/developers ?

**Comment by lukeabeck** [comment]
@Alexey666 our devs will follow up in your individual item here: https://github.com/Theme-Fusion/Localization-l10n/issues/45

**Comment by Alexey666** [comment]
Devi sent me to GitHub)
![img_4433](https://cloud.githubusercontent.com/assets/12021450/24878505/167a997e-1e3c-11e7-9f45-b195691aad56.PNG)

**Comment by lukeabeck** [comment]
Yes that was me, our developers will respond soon for you. I apologize for the delay.

**Comment by maximus80** [comment]
Hey everyone!

The above issue of POEdit not being able to open a .po file from the repo will only happen, if you download individual files. It seems that somehow the file encoding is changed by github.

Please always  just go here: https://github.com/Theme-Fusion/Localization-l10n and download the full zip: http://i.imgur.com/d8ve0j7.png

Then it will work without issues.
