### ISSUE TITLE
Extra characters in the translation

### ISSUE THREAD

**Issue by hassan-tariq** [Theme-Fusion/Localization-l10n#4]
There are extra characters in the 'Hello' String translation of Dutch files. Need to remove that %s

![2015-12-08_2139](https://cloud.githubusercontent.com/assets/5371053/11661591/7e919842-9df4-11e5-9e47-8d7023f570b9.png)

**Comment by hassan-tariq** [comment]
@maximus80 can we also update this? Got a ticket regarding this -> https://secure.helpscout.net/conversation/169311428/70108/?folderId=411825

**Comment by maximus80** [comment]
Yes.

Guys we will do a full catalogue update before the 4.0 release for all langs. So then all current translation strings will be in the files.
The translations of these strings is up to our users though. We can't check all translations as it is far too many strings, and we don't know the languages. Users can update the translations of the strings easily themselves.

We will introduce a new possibility for community changes of translation files in the fututre, to make this easier.
