### ISSUE TITLE
Russian translation for FB

### ISSUE THREAD

**Issue by lukeabeck** [Theme-Fusion/Localization-l10n#50]
From a user

> Ready Russian translation of fusion builder https://drive.google.com/file/d/0B0RX0imD8zOuV3EwWHRuaHI5ZVE/view

**Comment by lukeabeck** [comment]
Please check it over

**Comment by Alexey666** [comment]
Those files from me!) Thanks!

**Comment by lukeabeck** [comment]
We thank you 💯

**Comment by maximus80** [comment]
updated.
