### ISSUE TITLE
The zh_CH doesn't work.

### ISSUE THREAD

**Issue by alaxn** [Theme-Fusion/Localization-l10n#53]
I tried to apply the translation into Avada 5.2.1, but it failed. 

Tried many ways...Including change the strore files and review the theme files...

Finally, I updated those files into the Avada theme files, and it work.
[zh_CN.mo](http://7xivdl.com1.z0.glb.clouddn.com/zh_CN.mo)
[zh_CN.po](http://7xivdl.com1.z0.glb.clouddn.com/zh_CN.po)
I don't know where are the problems. However, it seems that the files in here are wrong.

**Comment by aristath** [comment]
@alaxn I just tested this and the translation files seem to be working fine for me.
Did you follow the instructions on https://theme-fusion.com/support/documentation/avada-documentation/#page-item-365853 ?

**Comment by alaxn** [comment]
Thank you for your test.  

I have found the problem: I did not download the translation files successfully so that the files are wrong.

At the same time, I find out it works if the translation files placed in the my-website/wp-content/themes/Avada/languages and rename as "zh_CN.mo" and "zh_CN.po".

Thanks again.

**Comment by aristath** [comment]
@alaxn please keep in mind that if you keep the translation files in `wp-content/themes/Avada/languages`, the files will be deleted when you update the theme.
It is recommended to keep language files in `wp-content/languages/themes` as documented on the link I posted above 👍
