### ISSUE TITLE
Cart Text

### ISSUE THREAD

**Issue by hassan-tariq** [Theme-Fusion/Localization-l10n#6]
Hi guys,

When you hover over the cart symbol, the drop-down opens. In that drop-down, it reads: 

Zur Kassa

In German, this should read 

**Zur Kasse**

Could you please change this on future updates?

Thank you and best regard

**Comment by lukeabeck** [comment]
@maximus80 can you confirm that should be changed?

**Comment by maximus80** [comment]
Well both are correct. Amazon e.g. uses the second one. So I changed it in the lang file.

**Comment by lukeabeck** [comment]
awesome, thx
