### ISSUE TITLE
Can't be opened in poedit

### ISSUE THREAD

**Issue by berlinone** [Theme-Fusion/Localization-l10n#70]
File can't be opened: "File may be corrupted or format not availbare."

**Comment by mikka23** [comment]
Hi @berlinone 

How are you downloading the file?  It sounds like this is a problem with the download rather than the actual file content.

**Comment by maximus80** [comment]
Hi @berlinone

Please see this issue for more information: https://github.com/Theme-Fusion/Localization-l10n/issues/39#issuecomment-293206540

For downloading of language files, please always just go here: https://github.com/Theme-Fusion/Localization-l10n and download the full zip: http://i.imgur.com/d8ve0j7.png

If you want to only download a single lang file, pleae navigate to it through the github file tree, e.g.
https://github.com/Theme-Fusion/Localization-l10n/blob/master/Avada/Avada-af.po, and right click the raw button: https://i.imgur.com/0MvlxvB.png for a direct file save.

These are the only valid possibilities to download files, and using one of those should fix your issue.

Thanks!
