### ISSUE TITLE
fusion-builder arabic language file.

### ISSUE THREAD

**Issue by mohammedays** [Theme-Fusion/Localization-l10n#73]
Hi and thank you all for the amazing theme. I am using the theme with an Arabic website, and I have copied the language file as directed. However, I notice that the fusion-builder file is not translated to Arabic or at least when I use the blog element (the meta info) are not translated. I just went a head and did the translation for my site. Here is the file if anyone would like to use it.

 Please tell me how to submit the new files.

Thank you all,

Peace, and Ramadan Kareem.

Mohammed

**Comment by aristath** [comment]
Hello Mohammed,

I apologise for the delay, we were preparing an update which is why it took us 4 days to get back to you.

You can zip the file and upload it here, or if you prefer you can [email us](mailto:info@theme-fusion.com), referencing this ticket as well so that we know what your email is about. 👍

**Comment by mohammedays** [comment]
HI please find the file attached.


________________________________

**Comment by aristath** [comment]
@mohammedays we never received a file for these, did you by any chance just attach a file to your reply in this email? If yes, then github strips attachments like that when posting a reply via email.
Can you please attach it by replying to the github ticket not via email but in the ticket's itself?

**Comment by mohammedays** [comment]
sure, please find the file attached.

**Comment by mikka23** [comment]
Unfortunately nothing is coming through on our end.  Is the attachment uploading okay? (Github only allows certain file types)

**Comment by mohammedays** [comment]
[fusion-builder-ar.zip](https://github.com/Theme-Fusion/Localization-l10n/files/2141703/fusion-builder-ar.zip)
it should be working now

**Comment by aristath** [comment]
Yes, this time we got the file. 👍 
I'll review the translations and update the repository accordingly. 
Thank you!

**Comment by aristath** [comment]
Translations reviewed and updated.
