### ISSUE TITLE
You Have X Items In Your Cart not translatable

### ISSUE THREAD

**Issue by Dekadinious** [Theme-Fusion/Localization-l10n#76]
Hello!

I can't seem to be able to translate the plural of You Have X Items In Your Cart.

**Comment by mikka23** [comment]
On which page are you seeing the string and in which language are you trying to translate?  All Avada specific strings should be translatable but if you let me know the answers to the above then I can check it out.

**Comment by Dekadinious** [comment]
It's in the cart in WooCommerce. I am trying to translate to Norwegian. The string is not present in the WooCommerce translation files. The string is present in singular form in the Avada translation file.

**Comment by mikka23** [comment]
Hi, both strings should be there, but you need to add a translation for both format (our example Norwegian files are missing the translation).  This will depend on what tool you are using for adding translations.  Using POedit for example it is like this:

<img width="602" alt="screenshot at may 30 12-14-22" src="https://user-images.githubusercontent.com/9296509/40714472-01675eec-6403-11e8-9ae5-dc04342c0aa0.png">

Notice how the singular form is the one you see listed but at the bottom there is an extra button to switch between singular and plural.

**Comment by Dekadinious** [comment]
I am using Loco Translation-plugin and sadly only get the singular form. I don't have any option to add a plural here. Is it a problem with Avada translations or Loco?

**Comment by mikka23** [comment]
I will check, but if that is the case that is a bad limitation of Loco translate.  Having the strings defined as singular/plural is the correct way to do this, since not all languages treat plurals in the same way.

**Comment by mikka23** [comment]
Hi, it should exist in Loco Translate as well.  Example:
<img width="1257" alt="screenshot at may 30 12-45-37" src="https://user-images.githubusercontent.com/9296509/40715893-68fff8da-6407-11e8-9b05-f7aa9fcf7d38.png">

**Comment by mikka23** [comment]
Attached the example files which are shown in screenshot:
[example.zip](https://github.com/Theme-Fusion/Localization-l10n/files/2053585/example.zip)

**Comment by Dekadinious** [comment]
The Loco-translation plugin should have that ability, but I don't know where it went wrong in that case. I do, however, remember that I translated the plural form as its own string earlier, but that it now is gone.

**Comment by Dekadinious** [comment]
This is weird. I will try to upload the Norwegian files again from scratch and see if that fixes it.

**Comment by Dekadinious** [comment]
That worked, must have been something with the file :)
