### ISSUE TITLE
String not taken into account in Avada/Avada-fr_FR.po file

### ISSUE THREAD

**Issue by Alphabc** [Theme-Fusion/Localization-l10n#77]
Hi,

It seems this sentence is not taken into account in Avada / Woocommerce:
![image](https://user-images.githubusercontent.com/24738945/40994320-39bc817a-68fc-11e8-8057-769dad8779ec.png)

Concerned file: Avada/Avada-fr_FR.po / mo

The english sentence remains on my website even though the other sentences are well translated.
I've added the very last file to be sure, and it is still the same...
It happened with at least previous and last version of Woocommerce, last version ov Avada

Moreover, the second string is not correctly translated:
please change:
msgstr[1] "Vous avez %d article dans votre panier"
to
msgstr[1] "Vous avez %d articles dans votre panier"

(for when it will work ;-) )

Thanks

**Comment by aristath** [comment]
@Alphabc from your screenshot I can see that this translation is marked as "fuzzy".
Have you tried removing the fuzzy tag from that?

**Comment by mikka23** [comment]
@Alphabc please also check here https://github.com/Theme-Fusion/Localization-l10n/issues/76

**Comment by Alphabc** [comment]
@aristath & @mikka23 : thanks... I check & come back to you

**Comment by Alphabc** [comment]
Just opened the po file on poedit, modified the plural that was not correct and saved: seems to work...
I did same for some other translations
Added https://github.com/Theme-Fusion/Localization-l10n/pull/78

Cheers

**Comment by Alphabc** [comment]
Merged by @aristath 
https://github.com/Theme-Fusion/Localization-l10n/pull/78
Thanks :+1:

**Comment by diagolise** [comment]
Buenos días, tenía problemas para la traducción de "You Have 2 Items In Your Cart"utilizo POEDIT he ajustado el singular y el plural para la cadena singular %d y para la plural %s pero sólo me traduce el singular...¿a qué es debido? estado repasando todas estas conversaciones pero no consigo traducir el plural...me podrían ayudar? adjunto una captura de pantalla del archivo Avada-es_ES.po


![image](https://user-images.githubusercontent.com/32894657/48952630-248f0480-ef43-11e8-9ff6-07378805cd49.png)

**Comment by mikka23** [comment]
Ese ejemplo es correcto.  Para el plural %s es correct y para el singular %d.  He actualizado los archivos

https://github.com/Theme-Fusion/Localization-l10n/blob/master/Avada/Avada-es_ES.po
https://github.com/Theme-Fusion/Localization-l10n/blob/master/Avada/Avada-es_ES.mo

Ejemplo en acción:
<img width="701" alt="screenshot at nov 23 16-30-30" src="https://user-images.githubusercontent.com/9296509/48953259-22c24280-ef3d-11e8-985b-31e69772964b.png">

**Comment by diagolise** [comment]
No entiendo por  qué no puedo descargar el archivo .po !! podrías pasarme el archivo adjunto por favor!!

**Comment by mikka23** [comment]
This is the direct link https://raw.githubusercontent.com/Theme-Fusion/Localization-l10n/master/Avada/Avada-es_ES.po

Or just download the entire zip again:
<img width="1117" alt="screenshot at nov 26 10-51-19" src="https://user-images.githubusercontent.com/9296509/49009753-4073ef80-f169-11e8-990b-387e9d4d2b3c.png">

**Comment by diagolise** [comment]
Gracias!, pero me sigue fallando el plural y ya no sé que puede ser.... he actualizado todos los archivos y rutas...

**Comment by mikka23** [comment]
Did you use the updated PO **and** MO? 
Did you also check that the files are the ones being used, eg they are not overwritten from somewhere else (change another string and test)?
Finally, did you also make sure to clear cache/change items in the cart to update the page?

**Comment by mikka23** [comment]
Also, do you have active theme support?  If so, please create a ticket with details.

**Comment by aristath** [comment]
>  Finally, did you also make sure to clear cache/change items in the cart to update the page?

This one is very important. WooCommerce saves the cart HTML as well as other strings in a cookie on your browser, so unless these are reset you won't see the fix - even if it is applied.
