### ISSUE TITLE
Language string not getting translated

### ISSUE THREAD

**Issue by puurinternet** [Theme-Fusion/Localization-l10n#90]
Hello,

We took over a Wordpress site with Woocommerce and Avada for a customer, and they had an issue with certain texts not getting translated to Dutch.
After finding out that there wasn't a language file for Avada yet, I used the one from this repository but there seems to be one string that doesn't get translated:

`#: includes/class-avada-woocommerce.php:1175
#. translators: Number.

msgid "You Have %d Item In Your Cart"
msgid_plural "You Have %s Items In Your Cart"
msgstr[0] "Je hebt %d artikel in je winkelmandje"
msgstr[1] "Je hebt %d artikelen in je winkelmandje"
`

although it is in the .po file.
Next I tried recompiling the .mo file again but that gave no different results.
After this I tried the files for different languages (german, and french), but in those languages the string isn't getting translated either.
Finally I checked the php file, and the msgid seems to match the one in the language file.

So I'm not really sure what the issue can be, maybe something went wrong with the conversion to the .mo file?

Any help is appreciated

**Comment by mikka23** [comment]
I have updated the Avada-nl_NL files in the repo.  If you re-download those they should work properly.  In particular I saw too issues.
1.  It was marked as a fuzzy translation
2.  The plural has the incorrect variable.  It had %d when it should be %s.

**Comment by puurinternet** [comment]
Thanks! That was the issue indeed.

The same thing seems to happen in the German and French files too. Maybe they copied the error from each other?
Not sure how easy it is to batch fix this, but that might be useful.

**Comment by mikka23** [comment]
Glad to hear that worked.  Yeah, this is something we should look to try and fix in the others as well.
